spring:
  application:
    name: uj-judge
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:mysecretpassword}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/db_ucb_judge}
    jpa:
      hibernate:
        ddl-auto: none
  zipkin:
    base-url: ${ZIPKIN_SERVER_URI:http://localhost:9411}

server:
  port: ${PORT:8081}

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8711/eureka}

keycloak:
  auth-server-url: ${KEYCLOAK_SERVER_URI:http://localhost:8090}
  autodetect-bearer-only: true
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:BNHREThKV64GqdjrJKJqkmLLowtwjfSi}
  realm: ${KEYCLOAK_REALM:ucb-judge}
  resource: ${KEYCLOAK_CLIENT_ID:uj-problems}
  ssl-required: none
  use-resource-role-mappings: false
  security-constraints:
    # TODO: add