spring:
  application:
    name: uj-judge
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:uj-submissions}
    password: ${RABBITMQ_PASSWORD:uj-submissions123}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:ucb-judge-rabbit}
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:mysecretpassword}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/db_ucb_judge}
    jpa:
      hibernate:
        ddl-auto: none
  zipkin:
    base-url: ${ZIPKIN_SERVER_URI:http://localhost:9411}

server:
  port: ${PORT:8081}

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8711/eureka}

keycloak:
  auth-server-url: ${KEYCLOAK_SERVER_URI:http://localhost:8090}
  autodetect-bearer-only: true
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:t3F8EFRanqv47XYA0oKwCJnYPisHsli1}
  realm: ${KEYCLOAK_REALM:ucb-judge}
  resource: ${KEYCLOAK_CLIENT_ID:uj-judge}
  ssl-required: none
  use-resource-role-mappings: false
  security-constraints:

aws:
  code-runner:
    url: ${AWS_CODE_RUNNER_URL:https://1i71fyddn3.execute-api.us-west-1.amazonaws.com/dev/code-runner}
    key: ${AWS_CODE_RUNNER_KEY:4zOVpxxxGcVsVY1VmLdT47GRDeX1M988GJpE9Mcg}